# Modèles de babana.ride, babana.driver, babana.motorcycle, etc. (lot L1, L4, L5).
from . import res_users
from . import res_partner
from . import babana_token
from . import babana_driver
from . import babana_driver_document
from . import babana_driver_decision
from . import babana_motorcycle
from . import babana_assignment
from . import babana_fare_rule
from . import babana_zone
from . import babana_route_cache
from . import babana_quote
from . import babana_ride
from . import babana_ride_state
from . import babana_idempotency_record
from . import babana_cash_movement
from . import babana_cash_remittance
from . import babana_cash_discrepancy
from . import babana_incident
from . import babana_ride_share
from . import babana_device_token
